# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codehere < Formula
  desc "Code project bootspraping tool"
  homepage "https://github.com/tsukinoko-kun/codehere"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/codehere/releases/download/v0.1.0/codehere_0.1.0_darwin_amd64.tar.gz"
      sha256 "8ce29f21995dfb273b2d2e8dc1015e2b8b04a0f28474311c6c57f6b8d1d8d902"

      def install
        bin.install "codehere"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/codehere/releases/download/v0.1.0/codehere_0.1.0_darwin_arm64.tar.gz"
      sha256 "c48dab0834dcf34015793cbf14e71d135965e8121de7f211174d9cbda606f2b5"

      def install
        bin.install "codehere"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/codehere/releases/download/v0.1.0/codehere_0.1.0_linux_amd64.tar.gz"
        sha256 "2ffbab3d4ae2bb15f4e14e248abd377234e4a874a764db1f07436ecbf50d8bee"

        def install
          bin.install "codehere"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/codehere/releases/download/v0.1.0/codehere_0.1.0_linux_arm64.tar.gz"
        sha256 "ddd4bc15832a1e7690038e915b1c4d5c84daefda94e9b635cf67e8a20da36c28"

        def install
          bin.install "codehere"
        end
      end
    end
  end
end
