# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codehere < Formula
  desc "Code project bootspraping tool"
  homepage "https://github.com/tsukinoko-kun/codehere"
  version "0.0.0"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/codehere/releases/download/v0.0.0/codehere_0.0.0_darwin_amd64.tar.gz"
      sha256 "6e53f98947ae2a6c1083bdf4b4cf5553eb59096a98e154f96e4d718a96c6ccfa"

      def install
        bin.install "codehere"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/codehere/releases/download/v0.0.0/codehere_0.0.0_darwin_arm64.tar.gz"
      sha256 "3999bd391b1db7f4d15c39cf365f0118073978b1515293f21d6eab2b49d9fa35"

      def install
        bin.install "codehere"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/codehere/releases/download/v0.0.0/codehere_0.0.0_linux_amd64.tar.gz"
        sha256 "6172434df87bc3ba70391cbd45a225c14fedb782a160f3c76aa470268231fecd"

        def install
          bin.install "codehere"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/codehere/releases/download/v0.0.0/codehere_0.0.0_linux_arm64.tar.gz"
        sha256 "7f788fb96173baf334abac1d0ba9ddf5f0274119dee235a65dd6d3d7f1597418"

        def install
          bin.install "codehere"
        end
      end
    end
  end
end
