# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devhosts < Formula
  desc "Hosts file manager for development environments"
  homepage "https://github.com/tsukinoko-kun/devhosts"
  version "0.0.0"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/devhosts/releases/download/v0.0.0/devhosts_0.0.0_darwin_amd64.tar.gz"
      sha256 "09d161c05696d9718eec5692ea09de1daa6d3a97d2436f9c4e1531332ab4cfb9"

      def install
        bin.install "devhosts"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/devhosts/releases/download/v0.0.0/devhosts_0.0.0_darwin_arm64.tar.gz"
      sha256 "6a695ccc77df90c0c3156e8455fed9499c559a2c212786b3fea89a1877572b45"

      def install
        bin.install "devhosts"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/devhosts/releases/download/v0.0.0/devhosts_0.0.0_linux_amd64.tar.gz"
        sha256 "cd7ca581f94d0d329ee9b43768131a7bc77d11edfb625e9054e3d388d7a6b8d7"

        def install
          bin.install "devhosts"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/devhosts/releases/download/v0.0.0/devhosts_0.0.0_linux_arm64.tar.gz"
        sha256 "d5bfea255ed89dea3ab93265b03135ad80299f93dd6a55a9d65eb3c2e6c79586"

        def install
          bin.install "devhosts"
        end
      end
    end
  end
end
