# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gqlc < Formula
  desc "GraphQL compiler"
  homepage "https://github.com/tsukinoko-kun/gqlc"
  version "1.1.1"
  license "Zlib"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tsukinoko-kun/gqlc/releases/download/v1.1.1/gqlc_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "4556d152497d230ca1c14f9fb822d61dd536c0e240d28634393a65ca94f26376"

      def install
        bin.install "gqlc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tsukinoko-kun/gqlc/releases/download/v1.1.1/gqlc_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "dc022f55b0c8186b196aa991a7bffd50df324ff0a5b1db2c4e5a07580fd75b64"

      def install
        bin.install "gqlc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsukinoko-kun/gqlc/releases/download/v1.1.1/gqlc_Linux_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "90e125291f5ae1be7e40128bde8a667536364803c2eb734a7e38f7c2b409b582"
      def install
        bin.install "gqlc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsukinoko-kun/gqlc/releases/download/v1.1.1/gqlc_Linux_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "7ee59933acc874ed782caa0a0b207d143ff3800a72d47fa065c08f821a6b55a4"
      def install
        bin.install "gqlc"
      end
    end
  end
end
