# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gqlc < Formula
  desc "GraphQL compiler"
  homepage "https://github.com/tsukinoko-kun/gqlc"
  version "1.0.4"
  license "Zlib"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tsukinoko-kun/gqlc/releases/download/v1.0.4/gqlc_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "41d5ad0cae5b87643bca36643fa627e56b33ba9ecd321a2b30612750ba305b4a"

      def install
        bin.install "gqlc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tsukinoko-kun/gqlc/releases/download/v1.0.4/gqlc_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "d67aace64bcd723189bc08b326c44f7ee888d16dd0f81650daad1e695c24353d"

      def install
        bin.install "gqlc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsukinoko-kun/gqlc/releases/download/v1.0.4/gqlc_Linux_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "db878ca229f03c0acb011fd5653e816eb569a6fcba767f1584d7d365a6cf4221"
      def install
        bin.install "gqlc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsukinoko-kun/gqlc/releases/download/v1.0.4/gqlc_Linux_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "8456cf689b6082ce27afae490a7dae5c7bca528af043beda57ccfd0f83684206"
      def install
        bin.install "gqlc"
      end
    end
  end
end
