# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gut < Formula
  desc "Git UI Tool"
  homepage "https://github.com/Frank-Mayer/gut"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Frank-Mayer/gut/releases/download/v0.2.0/gut_0.2.0_darwin_amd64.tar.gz"
      sha256 "1dbf6455f8cadbc6fc13447bbc0bf955f6186680fb86be30c53fade7334ffe85"

      def install
        bin.install "gut"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Frank-Mayer/gut/releases/download/v0.2.0/gut_0.2.0_darwin_arm64.tar.gz"
      sha256 "0a3af63c393275e09a007c2f687a9fd720025c8fd6fa3cc0ed90f6dc629ee74a"

      def install
        bin.install "gut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Frank-Mayer/gut/releases/download/v0.2.0/gut_0.2.0_linux_arm64.tar.gz"
      sha256 "0c78161cd978f7c1c8df8055451534322bae414322346eda6ea9171567ca90dd"

      def install
        bin.install "gut"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Frank-Mayer/gut/releases/download/v0.2.0/gut_0.2.0_linux_amd64.tar.gz"
      sha256 "4f3ad213359cf2067ce9da9d428323613fe17fd3a57fec02511e56252b73a6c0"

      def install
        bin.install "gut"
      end
    end
  end
end
