# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gut < Formula
  desc "Git UI Tool"
  homepage "https://github.com/Frank-Mayer/gut"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Frank-Mayer/gut/releases/download/v0.1.0/gut_0.1.0_darwin_arm64.tar.gz"
      sha256 "c1ab47fff0e1756074374e0762aa813d00f972dfbf94a72f8b43b08df552bbad"

      def install
        bin.install "gut"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Frank-Mayer/gut/releases/download/v0.1.0/gut_0.1.0_darwin_amd64.tar.gz"
      sha256 "e090b6274ab1906ac920c0fd84942d4962a2974b0dff8dfcc0e821ad219b5d20"

      def install
        bin.install "gut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Frank-Mayer/gut/releases/download/v0.1.0/gut_0.1.0_linux_arm64.tar.gz"
      sha256 "bf31e975d136785ce86e6396f638640af845b4b29f267f660d715e0b1d8fd4c8"

      def install
        bin.install "gut"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Frank-Mayer/gut/releases/download/v0.1.0/gut_0.1.0_linux_amd64.tar.gz"
      sha256 "b1e438e575b841d365c23f67771c50829c8a04010a62589c84183cdfccc959d5"

      def install
        bin.install "gut"
      end
    end
  end
end
