# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gut < Formula
  desc "Git UI Tool"
  homepage "https://github.com/Frank-Mayer/gut"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Frank-Mayer/gut/releases/download/v0.1.1/gut_0.1.1_darwin_arm64.tar.gz"
      sha256 "00f85b41ad3444930a9c873a49264d8a33efbb138fb3fff1360561a9539fd6b2"

      def install
        bin.install "gut"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Frank-Mayer/gut/releases/download/v0.1.1/gut_0.1.1_darwin_amd64.tar.gz"
      sha256 "ab64e35bba648807a553a8e5b6a93f76a76c5a9e50bae2d9c77ec883f00ef72f"

      def install
        bin.install "gut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Frank-Mayer/gut/releases/download/v0.1.1/gut_0.1.1_linux_arm64.tar.gz"
      sha256 "047a2bb1e18d70a7cdeac5f74e44793c383663af0680e6ac06b84c45aa13bb56"

      def install
        bin.install "gut"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Frank-Mayer/gut/releases/download/v0.1.1/gut_0.1.1_linux_amd64.tar.gz"
      sha256 "3e1034507ae656ad0869b9e982a34c3b7369995402ecf7d7849dbbe98e870d3c"

      def install
        bin.install "gut"
      end
    end
  end
end
