# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Headshot < Formula
  desc "C++ header file generator"
  homepage "https://github.com/tsukinoko-kun/headshot"
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/headshot/releases/download/v0.2.1/headshot_0.2.1_darwin_amd64.tar.gz"
      sha256 "4ea9239d8d0dfbcad1dfbbfd9200cf92ec2f00785fd235c98a7d5b568ca6f5a2"

      def install
        bin.install "headshot"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/headshot/releases/download/v0.2.1/headshot_0.2.1_darwin_arm64.tar.gz"
      sha256 "7a3d9a76c7dc2c2b21665cbfd9eb67e40ae2e2f58dc2bf8eecb52cf0df8341e3"

      def install
        bin.install "headshot"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/headshot/releases/download/v0.2.1/headshot_0.2.1_linux_amd64.tar.gz"
        sha256 "9cc386b4dc5960ef8716a762b05045428ac1ad702e9566b628dfc60365b0ff16"

        def install
          bin.install "headshot"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/headshot/releases/download/v0.2.1/headshot_0.2.1_linux_arm64.tar.gz"
        sha256 "4faae93ddfe739ca60dc4a72f92e7f7d3f70057cb022d855bc17b0c7470a1259"

        def install
          bin.install "headshot"
        end
      end
    end
  end
end
