# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Headshot < Formula
  desc "C++ header file generator"
  homepage "https://github.com/tsukinoko-kun/headshot"
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/headshot/releases/download/v1.0.1/headshot_1.0.1_darwin_amd64.tar.gz"
      sha256 "c9e53bb96180542a2ac7415b8ee1cc83a7fbe1aed9df69c7d8bd870b94dabe2b"

      def install
        bin.install "headshot"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/headshot/releases/download/v1.0.1/headshot_1.0.1_darwin_arm64.tar.gz"
      sha256 "cedc0c7c2ae969c1f382d5ab069d0793f9027c89ea3eec84a3a4a02cba3860ef"

      def install
        bin.install "headshot"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/headshot/releases/download/v1.0.1/headshot_1.0.1_linux_amd64.tar.gz"
        sha256 "c03b8b4c841b63866fcfdec155db9e96fa56c2a4e0331f9b7b1881e6d1b80262"

        def install
          bin.install "headshot"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/headshot/releases/download/v1.0.1/headshot_1.0.1_linux_arm64.tar.gz"
        sha256 "e157df69631290a386da8e17dcebedd22327d6210438485c6e00f1ecc7f4f085"

        def install
          bin.install "headshot"
        end
      end
    end
  end
end
