# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Headshot < Formula
  desc "C++ header file generator"
  homepage "https://github.com/tsukinoko-kun/headshot"
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/headshot/releases/download/v0.2.0/headshot_0.2.0_darwin_amd64.tar.gz"
      sha256 "9ba52fd66de4de94c31ba5a2ced3c1501ecb38682ae2e8b645f26c6b98ea0582"

      def install
        bin.install "headshot"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/headshot/releases/download/v0.2.0/headshot_0.2.0_darwin_arm64.tar.gz"
      sha256 "967efbd80a4afb11f3d5311506e5a28993b15c149ece0a32a2e0233f5a7392e8"

      def install
        bin.install "headshot"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/headshot/releases/download/v0.2.0/headshot_0.2.0_linux_amd64.tar.gz"
        sha256 "d35a61d8469cf4e55568e15967598e31320a1906773a79fafd95b5b5a898c862"

        def install
          bin.install "headshot"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/headshot/releases/download/v0.2.0/headshot_0.2.0_linux_arm64.tar.gz"
        sha256 "9f6d4b69210ddcbd4308cbcb5819a3c32ca5fa521353eb8e4262f88f2ede6b11"

        def install
          bin.install "headshot"
        end
      end
    end
  end
end
