# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class List < Formula
  desc "ls replacement"
  homepage "https://github.com/tsukinoko-kun/list"
  version "1.0.6"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/list/releases/download/v1.0.6/list_1.0.6_darwin_amd64.tar.gz"
      sha256 "20083569d5a383b250ea729babfc5b12b4af6881eba5b59fc71f5c13022097ac"

      def install
        bin.install "list"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/list/releases/download/v1.0.6/list_1.0.6_darwin_arm64.tar.gz"
      sha256 "5f04c7e1e79c239ee3bb1c85e067b1466d5619dee63014f39d2bd672e0f8a1a3"

      def install
        bin.install "list"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/list/releases/download/v1.0.6/list_1.0.6_linux_amd64.tar.gz"
        sha256 "6cc76800311640ea5c42470dd348ce21e97222762e19661d47e591d2d8b7d616"

        def install
          bin.install "list"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/list/releases/download/v1.0.6/list_1.0.6_linux_arm64.tar.gz"
        sha256 "f254ed8efa7a4afdcaa41a94d94604b6fff18649f83147fcccd469e2664f4910"

        def install
          bin.install "list"
        end
      end
    end
  end
end
