# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Netest < Formula
  desc "Network testing tool"
  homepage "https://github.com/tsukinoko-kun/netest"
  version "1.0.1"
  license "zlib"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/netest/releases/download/v1.0.1/netest_1.0.1_darwin_amd64.tar.gz"
      sha256 "d4ae39b3e24715002a5b67cc9b3b91c47f9fafe0bcdf5bf601c89cb2c5e33f6c"

      def install
        bin.install "netest"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/netest/releases/download/v1.0.1/netest_1.0.1_darwin_arm64.tar.gz"
      sha256 "08b29d0848a1ba68b8392c7048fa7e4e7c1fb65740da3a2ea1aa2d641b346c16"

      def install
        bin.install "netest"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/netest/releases/download/v1.0.1/netest_1.0.1_linux_amd64.tar.gz"
        sha256 "2567099a960096aa0a99c3c7e52ac5278d0d40f7e8e3e8b3824336b511140a86"

        def install
          bin.install "netest"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/netest/releases/download/v1.0.1/netest_1.0.1_linux_arm64.tar.gz"
        sha256 "965998d91f9d602d9ade3f8de9f2cccaf5a09649f82e67e5dffbb841d3581a12"

        def install
          bin.install "netest"
        end
      end
    end
  end
end
