# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Netest < Formula
  desc "Network testing tool"
  homepage "https://github.com/tsukinoko-kun/netest"
  version "1.0.0"
  license "zlib"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/netest/releases/download/v1.0.0/netest_1.0.0_darwin_amd64.tar.gz"
      sha256 "a5f854c9facff706620521f30e80f6af1383add66a520d3b4880da53981698a6"

      def install
        bin.install "netest"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/netest/releases/download/v1.0.0/netest_1.0.0_darwin_arm64.tar.gz"
      sha256 "adcda68b364daa0c0c2fe95d41a44e4e10c046aa8120c3fb81b698f6a7b52ba7"

      def install
        bin.install "netest"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/netest/releases/download/v1.0.0/netest_1.0.0_linux_amd64.tar.gz"
        sha256 "e85ff41688a17d244cc0f8d8ed0b4e9e30c7f52b3f4e9ffb6675f89f6083aaf4"

        def install
          bin.install "netest"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/netest/releases/download/v1.0.0/netest_1.0.0_linux_arm64.tar.gz"
        sha256 "5003f6b87aab39a9486908d70f730e39fdeb70dfae5e20d7dd36cce85f4b6a6b"

        def install
          bin.install "netest"
        end
      end
    end
  end
end
