# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Netest < Formula
  desc "Network testing tool"
  homepage "https://github.com/tsukinoko-kun/netest"
  version "1.1.0"
  license "zlib"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/netest/releases/download/v1.1.0/netest_1.1.0_darwin_amd64.tar.gz"
      sha256 "5940b98d53f8915a097043160fc8330119a787eaa39bd2dcb53d24b60c217b1c"

      def install
        bin.install "netest"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/netest/releases/download/v1.1.0/netest_1.1.0_darwin_arm64.tar.gz"
      sha256 "89079a9ccc1eacc556f279e07391eb16ec08d3ea0225e2ba69987d83a0cc54e1"

      def install
        bin.install "netest"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/netest/releases/download/v1.1.0/netest_1.1.0_linux_amd64.tar.gz"
        sha256 "96f264c99dac491d49ed9fcf1c11cbdef256886b0ee6dd4c8bf5b4cc5d61ecb2"

        def install
          bin.install "netest"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/netest/releases/download/v1.1.0/netest_1.1.0_linux_arm64.tar.gz"
        sha256 "a13f8df05519adc383b18ece9522ec6b309e14e0c41b641c2ffb31cf009a3d4c"

        def install
          bin.install "netest"
        end
      end
    end
  end
end
