# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ohmygosh < Formula
  desc "Interactive shell written in Go with a UI inspired by Warp"
  homepage "https://github.com/tsukinoko-kun/ohmygosh"
  version "1.0.0"
  license "MIT"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/ohmygosh/releases/download/v1.0.0/ohmygosh_1.0.0_darwin_amd64.tar.gz"
      sha256 "277a4a0c5c0471d21b9cc21d30f5e9b6b8d18f94fd3a71588d00fa1c74a5d236"

      def install
        bin.install "ohmygosh"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/ohmygosh/releases/download/v1.0.0/ohmygosh_1.0.0_darwin_arm64.tar.gz"
      sha256 "2b24c215d4dd9535fa19e8f9c735ef4f2a4de46569c06cb14ec2c4823fb114bf"

      def install
        bin.install "ohmygosh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/ohmygosh/releases/download/v1.0.0/ohmygosh_1.0.0_linux_amd64.tar.gz"
        sha256 "da015977f2551d5432e656e962ed8d2d648580e83f332481c84adffc82796a88"

        def install
          bin.install "ohmygosh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/ohmygosh/releases/download/v1.0.0/ohmygosh_1.0.0_linux_arm64.tar.gz"
        sha256 "36f832839bf8cc52e989d71962bd69ebdaed9384cf2e32a5cba548c1826e280b"

        def install
          bin.install "ohmygosh"
        end
      end
    end
  end
end
