# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ohmygosh < Formula
  desc "Interactive shell written in Go with a UI inspired by Warp"
  homepage "https://github.com/tsukinoko-kun/ohmygosh"
  version "1.1.0"
  license "MIT"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/ohmygosh/releases/download/v1.1.0/ohmygosh_1.1.0_darwin_amd64.tar.gz"
      sha256 "6784fdcc4a868010a7b60312313d231e77128d7d135b3b4b4704ddc51f4c0df7"

      def install
        bin.install "ohmygosh"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/ohmygosh/releases/download/v1.1.0/ohmygosh_1.1.0_darwin_arm64.tar.gz"
      sha256 "ef2b883d86daa98fdfcd5a9fb041b58e63a94aa82eba48218365dbfba2ce02a1"

      def install
        bin.install "ohmygosh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/ohmygosh/releases/download/v1.1.0/ohmygosh_1.1.0_linux_amd64.tar.gz"
        sha256 "a77a9e68eee24d906d5ff6b922ea901ec9179083848718f087dc5ec5acd35787"

        def install
          bin.install "ohmygosh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/ohmygosh/releases/download/v1.1.0/ohmygosh_1.1.0_linux_arm64.tar.gz"
        sha256 "ce75e8022e21439a9d34df0e014a158b8ee994ea7218a6b20809f1687a380a49"

        def install
          bin.install "ohmygosh"
        end
      end
    end
  end
end
