# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pogo < Formula
  desc "Centralized version control system"
  homepage "https://github.com/tsukinoko-kun/pogo"
  version "0.0.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/pogo/releases/download/v0.0.2/pogo_0.0.2_darwin_amd64.tar.gz"
      sha256 "27025a221fbdcb6c3ee914741fadcb195409a47cb2b4b1a8dddee6c0e51c93f6"

      def install
        bin.install "pogo"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/pogo/releases/download/v0.0.2/pogo_0.0.2_darwin_arm64.tar.gz"
      sha256 "8b65220895eb4437f09ba9b5fefb523b538da9c3ad3962349e4723b5768e76d0"

      def install
        bin.install "pogo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/pogo/releases/download/v0.0.2/pogo_0.0.2_linux_amd64.tar.gz"
        sha256 "cb2ee199620a31a71891f5d38ce845d77350b0beb853a3939a9938fbbc07fdea"

        def install
          bin.install "pogo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/pogo/releases/download/v0.0.2/pogo_0.0.2_linux_arm64.tar.gz"
        sha256 "78abac904ad72f1194acdebfb6b3544af90580380f9f041f6a56f45cc55d2197"

        def install
          bin.install "pogo"
        end
      end
    end
  end
end
