# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portal < Formula
  desc "Simple local file sharing"
  homepage "https://github.com/tsukinoko-kun/portal"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/portal/releases/download/v1.0.0/portal_1.0.0_darwin_amd64.tar.gz"
      sha256 "a469c2af171a39a3ac56e7b63716f15b79e9217d2b3ab748e6a0e031fce641e9"

      def install
        bin.install "portal"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/portal/releases/download/v1.0.0/portal_1.0.0_darwin_arm64.tar.gz"
      sha256 "9b912be7ec21608e3963f4bd4da8a32746dc79ea8ab5fb63353d549e231a126c"

      def install
        bin.install "portal"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/portal/releases/download/v1.0.0/portal_1.0.0_linux_amd64.tar.gz"
        sha256 "bc5c496652a4601feeab8df89f4c8af92d73f18a892a83ed7e2959a4234ece54"

        def install
          bin.install "portal"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/portal/releases/download/v1.0.0/portal_1.0.0_linux_arm64.tar.gz"
        sha256 "702cf1bbd04c76081911ac4fe845c77e19c6e7bd91a2093d4ba1d7c11e38f96c"

        def install
          bin.install "portal"
        end
      end
    end
  end
end
