# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portal < Formula
  desc "Simple local file sharing"
  homepage "https://github.com/tsukinoko-kun/portal"
  version "1.4.0"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/portal/releases/download/v1.4.0/portal_1.4.0_darwin_amd64.tar.gz"
      sha256 "743efe0bd1bd68ee3f344a7afde7733c1c35154c74ea3010c92c82fe93be8f42"

      def install
        bin.install "portal"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/portal/releases/download/v1.4.0/portal_1.4.0_darwin_arm64.tar.gz"
      sha256 "f7be5c414175534b803433fef361502161846e1bb10c9d7a6bd11747ece1ebf8"

      def install
        bin.install "portal"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/portal/releases/download/v1.4.0/portal_1.4.0_linux_amd64.tar.gz"
        sha256 "5ac7692ddbaee11df45ca37d9dc863e4014752f3831a7d66ac14489a450e1e11"

        def install
          bin.install "portal"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/portal/releases/download/v1.4.0/portal_1.4.0_linux_arm64.tar.gz"
        sha256 "24e366e2836df1d77d3f2c5d5c7500525a030d93fd86ffa6e9dca66d20d1fd95"

        def install
          bin.install "portal"
        end
      end
    end
  end
end
