# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RequestReview < Formula
  desc "Forgeless merge requests"
  homepage "https://github.com/tsukinoko-kun/request-review"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/request-review/releases/download/v0.1.0/request-review_0.1.0_darwin_amd64.tar.gz"
      sha256 "20d39f1132050eb64b715b7b8ae5d645349819244902ad060d2596abf6b59c65"

      def install
        bin.install "request-review"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/request-review/releases/download/v0.1.0/request-review_0.1.0_darwin_arm64.tar.gz"
      sha256 "cc5eecfc3af7f9f5499178d1c976a92209145fd694c8633e5418bd4826efc470"

      def install
        bin.install "request-review"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/request-review/releases/download/v0.1.0/request-review_0.1.0_linux_amd64.tar.gz"
        sha256 "af4a10749f677b97ecd3800e416e715c4024cd58e3f76329da393bfb94f9d6ee"

        def install
          bin.install "request-review"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/request-review/releases/download/v0.1.0/request-review_0.1.0_linux_arm64.tar.gz"
        sha256 "476c954c6e6ecc9947add85540ea425a8afd4f49564076eae956876500ec32a0"

        def install
          bin.install "request-review"
        end
      end
    end
  end
end
