# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RequestReview < Formula
  desc "Forgeless merge requests"
  homepage "https://github.com/tsukinoko-kun/request-review"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/request-review/releases/download/v0.1.0/request-review_0.1.0_darwin_amd64.tar.gz"
      sha256 "6f9747ab5c6a5ecd032d4275493b66c00fbc1bc6c8cc1083d3e58847093d9b97"

      def install
        bin.install "request-review"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/request-review/releases/download/v0.1.0/request-review_0.1.0_darwin_arm64.tar.gz"
      sha256 "2beaa3bfd229462f0dd02566d5b5c89be90928b13d5b839f666501ea26875ad6"

      def install
        bin.install "request-review"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/request-review/releases/download/v0.1.0/request-review_0.1.0_linux_amd64.tar.gz"
        sha256 "344ab71737632dc05a49202de9481242836395ef216e32fe3c575ef07147e5d0"

        def install
          bin.install "request-review"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/request-review/releases/download/v0.1.0/request-review_0.1.0_linux_arm64.tar.gz"
        sha256 "91eb69a2773851481e68fca7aaad1d404a0d18f23ada032d64c4d4144332ce42"

        def install
          bin.install "request-review"
        end
      end
    end
  end
end
