# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sedimentary < Formula
  desc "next generation source control"
  homepage "https://github.com/tsukinoko-kun/sedimentary"
  version "0.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tsukinoko-kun/sedimentary/releases/download/v0.0.0/sedimentary_0.0.0_darwin_amd64.tar.gz"
      sha256 "9759b2b3fc89315f4704eff0590104b719b25daf9cec7faf7e0f5dadb404de02"

      def install
        bin.install "sdmt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tsukinoko-kun/sedimentary/releases/download/v0.0.0/sedimentary_0.0.0_darwin_arm64.tar.gz"
      sha256 "0b6f9c5d7a4c76e8c7eb79ee6e1fc65b50e103c81b05c3cc17cae6eb3fe6099e"

      def install
        bin.install "sdmt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tsukinoko-kun/sedimentary/releases/download/v0.0.0/sedimentary_0.0.0_linux_amd64.tar.gz"
      sha256 "57650eaf07c4eaba41e207934cb6785c56e07f811a76eebd08f33a613c21b2dc"

      def install
        bin.install "sdmt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsukinoko-kun/sedimentary/releases/download/v0.0.0/sedimentary_0.0.0_linux_arm64.tar.gz"
      sha256 "249d87177ee3cfc82df9ad0a16f7d260bd05b3bf00aca7a94d774c79d94de6d1"

      def install
        bin.install "sdmt"
      end
    end
  end
end
