# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serve < Formula
  desc "Simple file server with a little extra"
  homepage "https://github.com/tsukinoko-kun/serve"
  version "2.3.2"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/serve/releases/download/v2.3.2/serve_2.3.2_darwin_amd64.tar.gz"
      sha256 "93ba714f2f95737c85beccac05c09e5a340fd616f3dfd3413b8e14916eeefd66"

      def install
        bin.install "serve"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/serve/releases/download/v2.3.2/serve_2.3.2_darwin_arm64.tar.gz"
      sha256 "9152ca684460538b5f6ed19490709fb2917738f7bfc3ed7b5b4a4b240bba770c"

      def install
        bin.install "serve"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/serve/releases/download/v2.3.2/serve_2.3.2_linux_amd64.tar.gz"
        sha256 "3ed87f84a56f242ae5bc25f36e9e5b289962944100b34aaae41dcca38b167baf"

        def install
          bin.install "serve"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/serve/releases/download/v2.3.2/serve_2.3.2_linux_arm64.tar.gz"
        sha256 "977a9073b11398a87b2267659f3eee22d6147fb24507c7c54f2b32ee9d6ab1be"

        def install
          bin.install "serve"
        end
      end
    end
  end
end
