# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smash < Formula
  desc "Cross platform interactive shell"
  homepage "https://github.com/tsukinoko-kun/smash"
  version "0.5.0"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/smash/releases/download/v0.5.0/smash_0.5.0_darwin_amd64.tar.gz"
      sha256 "d08c2313dda975fab043484271087ca74c6574732819037262626384df24687e"

      def install
        bin.install "smash"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/smash/releases/download/v0.5.0/smash_0.5.0_darwin_arm64.tar.gz"
      sha256 "09a0c2520d9c690dbf5c065d3144a859b35ebf6b7cbb34f9bb701619105281a4"

      def install
        bin.install "smash"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/smash/releases/download/v0.5.0/smash_0.5.0_linux_amd64.tar.gz"
        sha256 "d392c4ad17aaf79e0788df2b83932286969f43a81ccac841adcfb2aa3802ff4c"

        def install
          bin.install "smash"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/smash/releases/download/v0.5.0/smash_0.5.0_linux_arm64.tar.gz"
        sha256 "0dd45d5db04327acf752e01b0f62f3bad731e7aefa9f8a8c683b0d145c088d29"

        def install
          bin.install "smash"
        end
      end
    end
  end
end
