# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vend < Formula
  desc "Manage external sources easily"
  homepage "https://github.com/tsukinoko-kun/vend"
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/vend/releases/download/v1.0.1/vend_1.0.1_darwin_amd64.tar.gz"
      sha256 "a6bd5f10658cc15a4513e5ea57e71ff918012af2ea52ca64bcfa7755f7a9d497"

      def install
        bin.install "vend"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/vend/releases/download/v1.0.1/vend_1.0.1_darwin_arm64.tar.gz"
      sha256 "9b549e84fea43d104a2331d5b336bf8f2fbbe2d45eb64f4104931779f41bd05b"

      def install
        bin.install "vend"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/vend/releases/download/v1.0.1/vend_1.0.1_linux_amd64.tar.gz"
        sha256 "fb4a4634eb39f478fcef60be43b21fae62067040239d6fc7271080244cb18240"

        def install
          bin.install "vend"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/vend/releases/download/v1.0.1/vend_1.0.1_linux_arm64.tar.gz"
        sha256 "c148de8e6aa5921fa0516dbda1370b4e41a2cd638c1bcc6505c1dd7c4d75462d"

        def install
          bin.install "vend"
        end
      end
    end
  end
end
