# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vend < Formula
  desc "Manage external sources easily"
  homepage "https://github.com/tsukinoko-kun/vend"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/vend/releases/download/v1.0.0/vend_1.0.0_darwin_amd64.tar.gz"
      sha256 "b00995177c144fc005d6752f82da48b015fef2645cd52f02bfbd7c0bb38ac550"

      def install
        bin.install "vend"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/vend/releases/download/v1.0.0/vend_1.0.0_darwin_arm64.tar.gz"
      sha256 "a25d11e10b8087efd402428ca044d9eb81657913700ed3386977a186317ceab0"

      def install
        bin.install "vend"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/vend/releases/download/v1.0.0/vend_1.0.0_linux_amd64.tar.gz"
        sha256 "9741e947f2cbf930bf67da7ed8efffbf725a64b754aa390a8b4d82fbbd0b85db"

        def install
          bin.install "vend"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/vend/releases/download/v1.0.0/vend_1.0.0_linux_arm64.tar.gz"
        sha256 "f8afd39abf1789299eaad5c7659149958e3fe8e95fb0632f05a137ecad0f965c"

        def install
          bin.install "vend"
        end
      end
    end
  end
end
