# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yab < Formula
  desc "Yet another build tool"
  homepage "https://github.com/Frank-Mayer/yab"
  version "0.4.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Frank-Mayer/yab/releases/download/v0.4.2/yab_0.4.2_darwin_amd64.tar.gz"
      sha256 "115702290734c58fb02623dfcedb62d53810a4d3073b6aa0128c1c39d65e9f1a"

      def install
        bin.install "yab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Frank-Mayer/yab/releases/download/v0.4.2/yab_0.4.2_darwin_arm64.tar.gz"
      sha256 "2d60fe228c2b5ff368fcd0fcc232c5cf4a84b2c9e34aa266d9abb4ed4eae4fd4"

      def install
        bin.install "yab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Frank-Mayer/yab/releases/download/v0.4.2/yab_0.4.2_linux_amd64.tar.gz"
      sha256 "f07c8781ee53d67079da9ee3ebe43558e8accdb3a4ec0cddf872e77f0efff05f"

      def install
        bin.install "yab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Frank-Mayer/yab/releases/download/v0.4.2/yab_0.4.2_linux_arm64.tar.gz"
      sha256 "9021bc69c423099063ae97cef842b9789422b038d0ee6493bbed5c252ceafa7d"

      def install
        bin.install "yab"
      end
    end
  end
end
