# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yab < Formula
  desc "Yet another build tool"
  homepage "https://github.com/tsukinoko-kun/yab"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tsukinoko-kun/yab/releases/download/v0.6.1/yab_0.6.1_darwin_amd64.tar.gz"
      sha256 "18460a18aae943a5e4c16db042bd29594aa24af304ae3cf55369bec933aa389e"

      def install
        bin.install "yab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tsukinoko-kun/yab/releases/download/v0.6.1/yab_0.6.1_darwin_arm64.tar.gz"
      sha256 "42520f60a573b5092e11756af9ae396ddd671ebed04164d211844918e6440c94"

      def install
        bin.install "yab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tsukinoko-kun/yab/releases/download/v0.6.1/yab_0.6.1_linux_amd64.tar.gz"
      sha256 "b5caf375efd921eaaae1c6d8f9fe8dbb20ececf620c74d145ca1294b67fe5876"

      def install
        bin.install "yab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsukinoko-kun/yab/releases/download/v0.6.1/yab_0.6.1_linux_arm64.tar.gz"
      sha256 "4d331e1df6dc951f9601352e475a06e7bc96c4acf082367c8e42770110589b1d"

      def install
        bin.install "yab"
      end
    end
  end
end
