# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yab < Formula
  desc "Yet another build tool"
  homepage "https://github.com/Frank-Mayer/yab"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Frank-Mayer/yab/releases/download/v0.2.2/yab_0.2.2_darwin_arm64.tar.gz"
      sha256 "79ee1b17952f593a61bad217b0fea287aa354f1883585affb33f08ccdc96023d"

      def install
        bin.install "yab"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Frank-Mayer/yab/releases/download/v0.2.2/yab_0.2.2_darwin_amd64.tar.gz"
      sha256 "97022907b6d8a252fda5135678133c7fe3f80f83ebbd883f575679c8b1e31cf7"

      def install
        bin.install "yab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Frank-Mayer/yab/releases/download/v0.2.2/yab_0.2.2_linux_arm64.tar.gz"
      sha256 "ac4e2d0de18e7003fbde9cfef02b489f211730fd579320ad4c40ad81ab31ec35"

      def install
        bin.install "yab"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Frank-Mayer/yab/releases/download/v0.2.2/yab_0.2.2_linux_amd64.tar.gz"
      sha256 "39c0438d3cbda4a947dd3dccbaeec5e544f7769de618d240416869e8c7ad85fe"

      def install
        bin.install "yab"
      end
    end
  end
end
