# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zzh < Formula
  desc "Simple SSH wrapper"
  homepage "https://github.com/tsukinoko-kun/zzh"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/zzh/releases/download/v0.1.0/zzh_0.1.0_darwin_amd64.tar.gz"
      sha256 "0ef36eaa60299be73d68513febe344a5e65036ebc0318157b7bcd184c7558f38"

      def install
        bin.install "zzh"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/zzh/releases/download/v0.1.0/zzh_0.1.0_darwin_arm64.tar.gz"
      sha256 "a5a16aab951f6c4922b2b57310855bb018b78099bf7864c79c5fb01e6e1a613f"

      def install
        bin.install "zzh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/zzh/releases/download/v0.1.0/zzh_0.1.0_linux_amd64.tar.gz"
        sha256 "bb4f475d1a4398281ef6c7790c8bc222df14be8121b968ee1958a56aa0fe0064"

        def install
          bin.install "zzh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/zzh/releases/download/v0.1.0/zzh_0.1.0_linux_arm64.tar.gz"
        sha256 "3292ad93f7a6707cfb59823ae13baa0500793d43e53a708f7132706dffa79c1d"

        def install
          bin.install "zzh"
        end
      end
    end
  end
end
