# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zzh < Formula
  desc "Simple SSH wrapper"
  homepage "https://github.com/tsukinoko-kun/zzh"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/tsukinoko-kun/zzh/releases/download/v0.1.1/zzh_0.1.1_darwin_amd64.tar.gz"
      sha256 "4db27364a7ac5ec52fd71f9b084906ddc9a0171ce147a3776678e37193bda5b7"

      def install
        bin.install "zzh"
      end
    end
    on_arm do
      url "https://github.com/tsukinoko-kun/zzh/releases/download/v0.1.1/zzh_0.1.1_darwin_arm64.tar.gz"
      sha256 "633c37ca4d49009fc21a0d7a35c98ea429a2fe2141924474367dfa9dbd722d0a"

      def install
        bin.install "zzh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/zzh/releases/download/v0.1.1/zzh_0.1.1_linux_amd64.tar.gz"
        sha256 "aea310a9485899dbcf6085eed68c4313e3f652d305fdd1a0d45ae008adc97a66"

        def install
          bin.install "zzh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tsukinoko-kun/zzh/releases/download/v0.1.1/zzh_0.1.1_linux_arm64.tar.gz"
        sha256 "5238a2aae23581d68d88f4f09857935f6de1e50b581d8a17164ece36f9e234bb"

        def install
          bin.install "zzh"
        end
      end
    end
  end
end
